@LabLedger.Api_HostAddress = http://localhost:5143

### Register
POST {{LabLedger.Api_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "email": "scientist@lab.com",
  "password": "Password123!",
  "fullName": "Ada Scientist"
}

###

### Login
POST {{LabLedger.Api_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "scientist@lab.com",
  "password": "Password123!"
}

###

@auth_token = <paste token from login response>

### List samples
GET {{LabLedger.Api_HostAddress}}/api/samples
Authorization: Bearer {{auth_token}}

###

### Get sample by id
GET {{LabLedger.Api_HostAddress}}/api/samples/1
Authorization: Bearer {{auth_token}}

###

### Create sample
POST {{LabLedger.Api_HostAddress}}/api/samples
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "Blood Panel A",
  "type": "Blood",
  "origin": "Clinic North"
}

###
